# Generated by Django 5.1.3 on 2024-12-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidmetrics',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
