# Generated by Django 5.1.3 on 2024-12-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0003_remove_rfidmetrics_cattle_rfidmetrics_cattle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidmetrics',
            name='cattle_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
