# Generated by Django 5.1.3 on 2024-12-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0004_alter_rfidmetrics_cattle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
