# Generated by Django 5.1.3 on 2025-02-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0005_alter_cattle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='slaughter_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
