# Generated by Django 5.1.3 on 2025-02-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0006_alter_cattle_birth_weight_alter_cattle_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='nameCattle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
